# Generated by Django 5.0.4 on 2024-05-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecondEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('indian_tree_tshirt_size', models.CharField(max_length=20)),
                ('food_preference', models.CharField(max_length=20)),
                ('stay_arrangement', models.CharField(max_length=3)),
                ('first_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.firstevent')),
                ('second_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.secondevent')),
            ],
        ),
    ]
