# Generated by Django 5.0.4 on 2024-05-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_participant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstevent',
            name='first_event_choice',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firstevent',
            name='first_event_partner',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firstevent',
            name='p1_food_preference',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firstevent',
            name='p1_indian_tree_tshirt_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firstevent',
            name='p1_stay_arrangement',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='p1_food_preference',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='p1_indian_tree_tshirt_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='p1_stay_arrangement',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='second_event_choice',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='second_event_partner',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.firstevent'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='food_preference',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='indian_tree_tshirt_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='second_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.secondevent'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='stay_arrangement',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='whatsapp_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
