# Generated by Django 5.0.4 on 2024-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_firstevent_first_event_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstevent',
            name='p1_indian_tree_shorts_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='indian_tree_shorts_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='secondevent',
            name='p1_indian_tree_shorts_size',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firstevent',
            name='first_event_choice',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='secondevent',
            name='second_event_choice',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
