# Generated by Django 5.0.4 on 2024-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_card_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='point1',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='point2',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='point3',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='point4',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='card',
            name='point5',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
