# Generated by Django 5.0.4 on 2024-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_card_point1_alter_card_point2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondevent',
            old_name='p2_indian_tree_tshirt_size',
            new_name='p2_indian_tree_tshirts_size',
        ),
    ]
