# Generated by Django 5.0.4 on 2024-05-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_p2_indian_tree_tshirt_size_secondevent_p2_indian_tree_tshirts_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.firstevent'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='second_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.secondevent'),
        ),
    ]
