# Generated by Django 5.0.6 on 2024-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_participant_id_participant_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_event',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='second_event',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FirstEvent',
        ),
        migrations.DeleteModel(
            name='SecondEvent',
        ),
    ]
