# Generated by Django 5.0.6 on 2024-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_event_category',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='second_event_category',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
