# Generated by Django 5.0.6 on 2024-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_participant_first_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
