# Generated by Django 5.0.6 on 2024-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_participant_password_participant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(default=None, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='whatsapp_number',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
