# Generated by Django 5.0.6 on 2024-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_participant_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='first_event',
            new_name='first_event_id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='second_event',
            new_name='first_event_partner',
        ),
        migrations.AddField(
            model_name='participant',
            name='second_event_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='second_event_partner',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
