# Generated by Django 5.0.4 on 2024-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_first_event_participant_first_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(default=None, max_length=100, null=True)),
                ('seven', models.CharField(default=None, max_length=100, null=True)),
                ('nine', models.CharField(default=None, max_length=100, null=True)),
                ('hundrerd', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scndCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(default=None, max_length=100, null=True)),
                ('seven', models.CharField(default=None, max_length=100, null=True)),
                ('nine', models.CharField(default=None, max_length=100, null=True)),
                ('hundrerd', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
