# Generated by Django 5.0.4 on 2024-06-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_istcategory_scndcategory_remove_participant_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scndcategory',
            old_name='hundrerd',
            new_name='NineZero',
        ),
        migrations.RenameField(
            model_name='scndcategory',
            old_name='nine',
            new_name='OneTwoZero',
        ),
        migrations.RenameField(
            model_name='scndcategory',
            old_name='seven',
            new_name='OneZeroFive',
        ),
    ]
