# Generated by Django 5.0.4 on 2024-06-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_hundrerd_scndcategory_ninezero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='istcategory',
            old_name='hundrerd',
            new_name='NineZero',
        ),
        migrations.RenameField(
            model_name='istcategory',
            old_name='nine',
            new_name='OneTwoZero',
        ),
        migrations.RenameField(
            model_name='istcategory',
            old_name='seven',
            new_name='OneZeroFive',
        ),
    ]
