# Generated by Django 5.0.4 on 2024-06-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_firsteventname_event_id_secondeventname_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsteventname',
            name='category',
        ),
        migrations.RemoveField(
            model_name='secondeventname',
            name='category',
        ),
        migrations.DeleteModel(
            name='FirstEventCategory',
        ),
        migrations.DeleteModel(
            name='FirstEventName',
        ),
        migrations.DeleteModel(
            name='SecondEventCategory',
        ),
        migrations.DeleteModel(
            name='SecondEventName',
        ),
    ]
