# Generated by Django 5.0.4 on 2024-06-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_bankdetail_event_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='bank_detail',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='event',
        ),
        migrations.DeleteModel(
            name='BankDetail',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
