# Generated by Django 5.0.4 on 2024-07-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_teamforfirstevent_teamforsecondevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamforsecondevent',
            name='first_partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.participant'),
        ),
    ]
